### ISSUE TITLE
General html and server html conflicts

### ISSUE THREAD

**Issue by MilosS2024** [hengsong829/foodview-html-css-aus-2020-1-2-#1]
I have a issue for conflicting of html context
So I was going to work server html contract to local
But Such this issue occurs..
"Change html context or server ip address..."

**Comment by TuanThai1030** [comment]
What is the framework you've used for building?
According to my experience, I've changed react script version, and then such that issue has never been.
But I think you need to focus on your framwork type and version
Thank you in advance!

**Comment by softengKing** [comment]
What is the framework you've used for?
According to my experience, I've changed react script version and babel config and then solved such that issue
So I suggest you need to focus script version
Thank you
